### ISSUE TITLE
Permission problem 

### ISSUE THREAD

**Issue by eepakpro** [lMartin3/BetterShulkerBoxesRewritten#54]
when ever I try to use the plugin it says no permission . so how can I grant permission for the plugin in my aternos server pls help ..

**Comment by Hutch79** [comment]
Hey @eepakpro 
Have you installed a Permission plugin like LuckPerms?
If so, have you set the permissions?

If you have no permission plugin installed, here is a video explaining LuckPerms --> https://youtu.be/GtjdZYke5cA
You'll find the required Permissions on the SpigotMC page. --> https://www.spigotmc.org/resources/58837/

**Comment by eepakpro** [comment]
Thx a lot

**Comment by Hutch79** [comment]
No problem!
If something doesn't work as intended, don't hesitate to ask ^^

**Comment by eepakpro** [comment]
Sir wont the bettershulkebox plugin won't work without the luckperm? Cuz
it's very complicated task so my servers admin hesitating to do it.

**Comment by Hutch79** [comment]
If I'm not mistaken, there is an option to turn off the permissions.

But I really recommend you to learn how permissions work.
Nearly every Plugin has permissions built into it, since that is the standardized way of telling the plugin, which user is allowed to do what.
For example, you have ranks on your server, and you only want the premium rank to be able to use Bettershulkerboxes but not normal players. This would only be possible with the use of Permissions.

Also, other Plugins like EssentialsX have no option of not using Permissions.

I get that it's hard to get your head around these permissions, it took me a while to, but these are the "industry standard" of configuring the rights per player.
The best way to learn them is a little test server with no OP (`/op Player`) since op has a lot of permissions by default.
YouTube as well as Google are a grate help to learn how Luckperms works. And if you figure it out, there is nothing stopping you configuring your Server features, even on a per world or dimension level.
