### ISSUE TITLE
BSB doesn't work

### ISSUE THREAD

**Issue by DaddyRobLIVE** [lMartin3/BetterShulkerBoxesRewritten#57]
![image](https://user-images.githubusercontent.com/109517972/235820306-d1b1bba8-93ce-4cef-98a7-b3c450977b63.png)

using the latest version of Paper 
![image](https://user-images.githubusercontent.com/109517972/235820341-74d801b9-cbd9-43f1-b5ab-070ae00578ce.png)

**Comment by DaddyRobLIVE** [comment]
![image](https://user-images.githubusercontent.com/109517972/235820442-769aa2f0-5fd7-4dfc-ba0f-6ef7f5e25798.png)
did you like found an exploit so you've disabled the plugin?

**Comment by Akiyama-mikagami** [comment]
I Also find this problem.I used the latest version,but it still tells me to update the plugin and doesn't work

**Comment by Hutch79** [comment]
Hey,

This message is intended to show up since there is a dupe bug in the newest Version.
Unfortunately, lMartin3 has currently no time to fix this.

The bug only affects the `right click on inventory` feature, so if you disable this, you should be good to go!
For the Plugin to not disable itself, you also need to disable `vulnerable version check`.

If you want to see the official statement of lMartin3, you can do so on his Discord in the Announcements channel.
https://discord.com/channels/546014271461523456/546042327794450432/1103034517972852819
