### ISSUE TITLE
I have used the latest version,but it still tells me to update the plugin

### ISSUE THREAD

**Issue by Akiyama-mikagami** [lMartin3/BetterShulkerBoxesRewritten#58]
I have used the latest version4.1.1,but it still tells me to update the plugin and the plugin doesn't work

**Comment by Hutch79** [comment]
Hey,

This message is intended to show up since there is a dupe bug in the newest Version.
Unfortunately, lMartin3 has currently no time to fix this.

The bug only affects the `right click on inventory` feature, so if you disable this, you should be good to go!
For the Plugin to not disable itself, you also need to disable `vulnerable version check`.

If you want to see the official statement of lMartin3, you can do so on his Discord in the Announcements channel.
https://discord.com/channels/546014271461523456/546042327794450432/1103034517972852819

**Comment by Hutch79** [comment]
I'll close this issue since it's a duplicate of #57
