### ISSUE TITLE
The plugin disabled the features to prevent exploitation

### ISSUE THREAD

**Issue by TomHo41** [lMartin3/BetterShulkerBoxesRewritten#59]
CONSOLE: 
```
WARNING! You are currently using a vulnerable version of Better Shulker Boxes!
The plugin disabled the features to prevent exploitation
```
VERSION:
BetterShulkerBoxesRewritten-4.1.1
Paper - 1.19.3

**Comment by Hutch79** [comment]
Hey,

This message is intended to show up since there is a dupe bug in the newest Version.
Unfortunately, lMartin3 has currently no time to fix this.

The bug only affects the `right click on inventory` feature, so if you disable this, you should be good to go!
For the Plugin to not disable itself, you also need to disable `vulnerable version check`.

If you want to see the official statement of lMartin3, you can do so on his Discord in the Announcements channel.
https://discord.com/channels/546014271461523456/546042327794450432/1103034517972852819

**Comment by Hutch79** [comment]
I'll close this issue since it's a duplicate of #57
